name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Check formatting
        run: uv run ruff format src tests --check
      - name: Type check
        run: uv run mypy src tests
      - name: Lint
        run: uv run ruff check src tests
      - name: Run tests
        run: |
          tests/create_test_db.sh
          uv run pytest
